#!/bin/bash

# check if running as root
if [ $EUID -ne 0 ]; then
	echo "This script must be run as root."
	exit 1
fi

# check if target module name provided
if [ $# -le 0 ]; then
	echo "Usage: install_tgt <tgt-basename>"
	exit 2
fi

# check if target module source code exists
if [ ! -f $1.c ]; then
	echo "Target module source ($1.c) not found."
fi

# remove existing target module if resinstalling
if [ -e iverilog/lib/ivl/$1.tgt ]; then
	rm iverilog/lib/ivl/$1.tgt
fi

# remove existing configuration files if reinstalling
if [ -e iverilog/lib/ivl/$1.conf ]; then
	rm iverilog/lib/ivl/$1.conf
fi
if [ -e iverilog/lib/ivl/$1-s.conf ]; then
	rm iverilog/lib/ivl/$1-s.conf
fi

# compile and install target module
gcc -o $1.tgt -fpic -shared $1.c
mv $1.tgt iverilog/lib/ivl/$1.tgt

# create simulation configuration file
echo "functor:cprop
functor:nodangle
-t:dll
flag:DLL=$1.tgt" > iverilog/lib/ivl/$1.conf

# create synthesis configuration file
echo "functor:synth2
functor:synth
functor:syn-rules
functor:cprop
functor:nodangle
-t:dll
flag:DLL=$1.tgt" > iverilog/lib/ivl/$1-s.conf

exit 0
