
// Generated by Cadence Genus(TM) Synthesis Solution 16.11-s015_1
// Generated on: Jun 28 2017 11:20:02 EDT (Jun 28 2017 15:20:02 UTC)

// Verification Directory fv/up_counter 

module increment_unsigned(A, CI, Z);
  input [7:0] A;
  input CI;
  output [7:0] Z;
  wire [7:0] A;
  wire CI;
  wire [7:0] Z;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35;
  assign Z[0] = 1'b0;
  SEN_AO21_1 g49(.A1 (A[7]), .A2 (n_33), .B (n_34), .X (n_35));
  SEN_AN2_1 g50(.A1 (n_20), .A2 (n_19), .X (n_34));
  SEN_INV_1 g51(.A (n_19), .X (n_33));
  SEN_ADDH_2 g52(.A (n_6), .B (n_15), .CO (n_32), .S (n_31));
  SEN_ADDH_2 g53(.A (n_11), .B (n_14), .CO (n_29), .S (n_30));
  SEN_ADDH_2 g54(.A (n_9), .B (n_18), .CO (n_27), .S (n_28));
  SEN_ADDH_2 g55(.A (n_8), .B (n_17), .CO (n_25), .S (n_26));
  SEN_ADDH_2 g56(.A (n_7), .B (n_16), .CO (n_23), .S (n_24));
  SEN_ADDH_2 g57(.A (n_10), .B (n_12), .CO (n_21), .S (n_22));
  SEN_INV_1 g58(.A (A[7]), .X (n_20));
  SEN_BUF_1P5 drc(.A (n_32), .X (n_19));
  SEN_BUF_1P5 drc_bufs(.A (n_25), .X (n_18));
  SEN_BUF_1P5 drc_bufs62(.A (n_23), .X (n_17));
  SEN_BUF_1P5 drc_bufs63(.A (n_21), .X (n_16));
  SEN_BUF_1P5 drc_bufs64(.A (n_29), .X (n_15));
  SEN_BUF_1P5 drc_bufs65(.A (n_27), .X (n_14));
  SEN_BUF_1P5 drc_bufs71(.A (A[0]), .X (n_12));
  SEN_BUF_1P5 drc_bufs72(.A (A[5]), .X (n_11));
  SEN_BUF_1P5 drc_bufs73(.A (A[1]), .X (n_10));
  SEN_BUF_1P5 drc_bufs74(.A (A[4]), .X (n_9));
  SEN_BUF_1P5 drc_bufs75(.A (A[3]), .X (n_8));
  SEN_BUF_1P5 drc_bufs76(.A (A[2]), .X (n_7));
  SEN_BUF_1P5 drc_bufs77(.A (A[6]), .X (n_6));
  SEN_BUF_1P5 drc_bufs78(.A (n_28), .X (Z[4]));
  SEN_BUF_1P5 drc_bufs79(.A (n_22), .X (Z[1]));
  SEN_BUF_1P5 drc_bufs80(.A (n_26), .X (Z[3]));
  SEN_BUF_1P5 drc_bufs81(.A (n_30), .X (Z[5]));
  SEN_BUF_1P5 drc_bufs82(.A (n_24), .X (Z[2]));
  SEN_BUF_1P5 drc_bufs83(.A (n_31), .X (Z[6]));
  SEN_BUF_D_2 drc89(.A (n_35), .X (Z[7]));
endmodule

module up_counter(out, enable, clk, reset);
  input enable, clk, reset;
  output [7:0] out;
  wire enable, clk, reset;
  wire [7:0] out;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, n_0, n_1, n_2, n_3, n_4, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  increment_unsigned inc_add_27_14_1(.A ({n_40, n_41, n_42, n_43, n_44,
       n_45, n_46, n_47}), .CI (1'b1), .Z ({n_49, n_50, n_51, n_52,
       n_53, n_54, n_55, UNCONNECTED}));
  SEN_BUF_24 g27(.A (n_47), .X (out[0]));
  SEN_BUF_24 g25(.A (n_43), .X (out[4]));
  SEN_BUF_24 g21(.A (n_45), .X (out[2]));
  SEN_BUF_24 g24(.A (n_44), .X (out[3]));
  SEN_BUF_24 g23(.A (n_42), .X (out[5]));
  SEN_BUF_24 g20(.A (n_41), .X (out[6]));
  SEN_BUF_24 g22(.A (n_40), .X (out[7]));
  SEN_BUF_24 g26(.A (n_46), .X (out[1]));
  SEN_FSDPQO_4 \out_reg[3] (.CK (clk), .D (n_21), .SI (1'b0), .SE
       (1'b0), .Q (n_27), .SO (UNCONNECTED0));
  SEN_FSDPQO_4 \out_reg[2] (.CK (clk), .D (n_19), .SI (1'b0), .SE
       (1'b0), .Q (n_26), .SO (UNCONNECTED1));
  SEN_FSDPQO_4 \out_reg[4] (.CK (clk), .D (n_22), .SI (1'b0), .SE
       (1'b0), .Q (n_28), .SO (UNCONNECTED2));
  SEN_FSDPQO_4 \out_reg[0] (.CK (clk), .D (n_16), .SI (1'b0), .SE
       (1'b0), .Q (n_24), .SO (UNCONNECTED3));
  SEN_FSDPQO_4 \out_reg[6] (.CK (clk), .D (n_20), .SI (1'b0), .SE
       (1'b0), .Q (n_30), .SO (UNCONNECTED4));
  SEN_FSDPQO_4 \out_reg[5] (.CK (clk), .D (n_23), .SI (1'b0), .SE
       (1'b0), .Q (n_29), .SO (UNCONNECTED5));
  SEN_FSDPQO_4 \out_reg[1] (.CK (clk), .D (n_18), .SI (1'b0), .SE
       (1'b0), .Q (n_25), .SO (UNCONNECTED6));
  SEN_FSDPQO_4 \out_reg[7] (.CK (clk), .D (n_17), .SI (1'b0), .SE
       (1'b0), .Q (n_31), .SO (UNCONNECTED7));
  SEN_AN2_S_1P5 g30(.A1 (n_7), .A2 (n_15), .X (n_23));
  SEN_AN2_S_1P5 g31(.A1 (n_7), .A2 (n_14), .X (n_22));
  SEN_AN2_S_1P5 g32(.A1 (n_7), .A2 (n_13), .X (n_21));
  SEN_AN2_S_1P5 g33(.A1 (n_7), .A2 (n_12), .X (n_20));
  SEN_AN2_S_1P5 g34(.A1 (n_7), .A2 (n_11), .X (n_19));
  SEN_AN2_S_1P5 g35(.A1 (n_7), .A2 (n_9), .X (n_18));
  SEN_AN2_S_1P5 g36(.A1 (n_7), .A2 (n_10), .X (n_17));
  SEN_AN2_S_1P5 g37(.A1 (n_7), .A2 (n_8), .X (n_16));
  SEN_MUX2_1 g38(.D0 (n_29), .D1 (n_51), .S (n_2), .X (n_15));
  SEN_MUX2_1 g39(.D0 (n_28), .D1 (n_52), .S (n_2), .X (n_14));
  SEN_MUX2_1 g40(.D0 (n_27), .D1 (n_53), .S (n_2), .X (n_13));
  SEN_MUX2_1 g41(.D0 (n_30), .D1 (n_50), .S (n_2), .X (n_12));
  SEN_MUX2_1 g42(.D0 (n_26), .D1 (n_54), .S (n_0), .X (n_11));
  SEN_MUX2_1 g43(.D0 (n_31), .D1 (n_49), .S (n_2), .X (n_10));
  SEN_MUX2_1 g44(.D0 (n_25), .D1 (n_55), .S (n_2), .X (n_9));
  SEN_MUX2_1 g45(.D0 (n_2), .D1 (n_6), .S (n_24), .X (n_8));
  SEN_INV_S_4 g46(.A (n_3), .X (n_7));
  SEN_INV_3 g47(.A (n_0), .X (n_6));
  SEN_BUF_6 drc_bufs61(.A (n_24), .X (n_47));
  SEN_BUF_6 drc_bufs65(.A (n_31), .X (n_40));
  SEN_BUF_6 drc_bufs69(.A (n_27), .X (n_44));
  SEN_BUF_6 drc_bufs73(.A (n_26), .X (n_45));
  SEN_BUF_6 drc_bufs77(.A (n_25), .X (n_46));
  SEN_BUF_6 drc_bufs81(.A (n_30), .X (n_41));
  SEN_BUF_6 drc_bufs85(.A (n_29), .X (n_42));
  SEN_BUF_6 drc_bufs89(.A (n_28), .X (n_43));
  SEN_INV_2 drc_bufs93(.A (n_4), .X (n_1));
  SEN_BUF_1P5 drc_bufs103(.A (reset), .X (n_3));
  SEN_BUF_1P5 drc_bufs108(.A (enable), .X (n_4));
  SEN_INV_S_6 drc_bufs142(.A (n_1), .X (n_2));
  SEN_BUF_3 drc148(.A (n_2), .X (n_0));
endmodule

